

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/navbar/Navbar";
import Footer from "./_component/navbar/footer/Footer";
import { Toaster } from "react-hot-toast";
import Nextauthprovider from "./provider/nextauthprovider"
import Providers from "./provider/react-qurey-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        <Nextauthprovider>

          <Toaster />
          <Navbar />
          <div className="container mx-auto max-w-7xl">{children}</div>
          <Footer />
        </Nextauthprovider>
          
       </Providers>



      </body>
    </html>
  );
}
